name: Native Windows ARM64 Build

on: [push, pull_request]

jobs:
  build:
    # Use the native Windows ARM64 runner image
    runs-on: windows-11-arm

    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          # Pin your required version or use "25.x" for minor matching
          # version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Protoc Installation
        run: protoc --version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc

      - name: Build and Test Natively
        run: |
          cargo build --target aarch64-pc-windows-msvc --release
          cargo test --target aarch64-pc-windows-msvc --release

      # Recursive list using PowerShell (default shell on Windows runners)
      - name: List all files recursively (PowerShell)
        if: always()
        run: Get-ChildItem -Recurse


      #- name: Download scc
      #  run: |
      #    Invoke-WebRequest -Uri "https://github.com/boyter/scc/releases/download/v3.7.0/scc_Windows_x86_64.zip" -OutFile scc.zip
      #    Expand-Archive scc.zip -DestinationPath .

      #- name: Run scc
      #  run: ./scc.exe .
      # --- UPLOAD ARTIFACTS STEP ---
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          #name: testing-build       # The name of your downloadable zip file
          path: target/                  # The directory or file path to upload
          retention-days: 7            # Optional: How long to keep the files (Default: 90)
          if-no-files-found: error     # Optional: Fails the build if 'dist' is missing
